name: delete package ci

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'package name'
        required: true

jobs:

  delete:

    runs-on: ubuntu-latest

    steps:

      - name: delete package versions
        uses: actions/delete-package-versions@v1.0.3
        with:
          package-name: ${{ github.event.inputs.package }}
