name: spring-oxygen publish ci

#on:
#  release:
#    types: [created]

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout code
      uses: actions/checkout@v2

    - name: cache gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: setup jdk env
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: build jar
      run: gradle build -x test

    - name: publish jar
      run: gradle publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
